// 恢复持久化数据
export const REDUX_STORAGE_KEY = "redux-persist";

// 在初始化水合完成前，这里都保持false，避免，一边水合一边又存一遍
export const rehydrateFlag = { flag: false };

export const REHYDRATE_KEYS = {
  SETTING_TRANSCRIPTION_URL: "SETTING_TRANSCRIPTION_URL",
  SETTING_TRANSCRIPTION_MODEL: "SETTING_TRANSCRIPTION_MODEL",
  SETTING_TRANSCRIPTION_TOKEN: "SETTING_TRANSCRIPTION_TOKEN",
  SETTING_OPENAI_API_URL: "SETTING_OPENAI_API_URL",
  SETTING_OPENAI_TOKEN: "SETTING_OPENAI_TOKEN",
  SETTING_OPENAI_MODEL: "SETTING_OPENAI_MODEL",
  SETTING_OUTPUT_TEMPLATE: "SETTING_OUTPUT_TEMPLATE",
  SETTING_BATCH_TRANSLATE: "SETTING_BATCH_TRANSLATE",
  SETTING_LANGUAGE: "SETTING_LANGUAGE",
  SETTING_OCR_TARGET_LANGUAGE: "SETTING_OCR_TARGET_LANGUAGE",
  SETTING_THEME: "SETTING_THEME",
  SETTING_PANEL_EXPANSION: "SETTING_PANEL_EXPANSION",
  SETTING_API_PROVIDER_TYPE: "SETTING_API_PROVIDER_TYPE",
  SETTING_OMNI_KEEP_AUDIO_TYPE: "SETTING_OMNI_KEEP_AUDIO_TYPE",
};

export enum EApiProviderType {
  CUSTOM = "custom",
  /** Omni类型的模型运行 */
  OMNI = "OMNI",
}
