// 恢复持久化数据
export const REDUX_STORAGE_KEY = "redux-persist";

// 在初始化水合完成前，这里都保持false，避免，一边水合一边又存一遍
export const rehydrateFlag = { flag: false };

export const REHYDRATE_KEYS = {
  SETTING_TRANSCRIPTION_URL: "SETTING_TRANSCRIPTION_URL",
  SETTING_TRANSCRIPTION_MODEL: "SETTING_TRANSCRIPTION_MODEL",
  SETTING_TRANSCRIPTION_TOKEN: "SETTING_TRANSCRIPTION_TOKEN",
  SETTING_OPENAI_API_URL: "SETTING_OPENAI_API_URL",
  SETTING_OPENAI_TOKEN: "SETTING_OPENAI_TOKEN",
  SETTING_OPENAI_MODEL: "SETTING_OPENAI_MODEL",
  SETTING_AI_TEMPLATE: "SETTING_AI_TEMPLATE",
  SETTING_LANGUAGE: "SETTING_LANGUAGE",
  SETTING_API_PROVIDER_TYPE: "SETTING_API_PROVIDER_TYPE",
  SETTING_LONGCAT_API_AUTH: "SETTING_LONGCAT_API_AUTH",
};

export enum EApiProviderType {
  CUSTOM = "custom",
  LONG_CAT = "longcat",
}
