// 恢复持久化数据
export const REDUX_STORAGE_KEY = "redux-persist";

// 在初始化水合完成前，这里都保持false，避免，一边水合一边又存一遍
export const rehydrateFlag = { flag: false };

export const REHYDRATE_KEYS = {
  SETTING_TRANSCRIPTION_URL: "SETTING_TRANSCRIPTION_URL",
  SETTING_TRANSCRIPTION_MODEL: "SETTING_TRANSCRIPTION_MODEL",
  SETTING_TRANSCRIPTION_TOKEN: "SETTING_TRANSCRIPTION_TOKEN",
  SETTING_OPENAI_API_URL: "SETTING_OPENAI_API_URL",
  SETTING_OPENAI_TOKEN: "SETTING_OPENAI_TOKEN",
  SETTING_OPENAI_MODEL: "SETTING_OPENAI_MODEL",
  SETTING_AI_TEMPLATE: "SETTING_AI_TEMPLATE",
  SETTING_OUTPUT_TEMPLATE: "SETTING_OUTPUT_TEMPLATE",
  SETTING_TARGET_LANGUAGES: "SETTING_TARGET_LANGUAGES",
  SETTING_BATCH_TRANSLATE: "SETTING_BATCH_TRANSLATE",
  SETTING_LANGUAGE: "SETTING_LANGUAGE",
  SETTING_API_PROVIDER_TYPE: "SETTING_API_PROVIDER_TYPE",
  SETTING_LONGCAT_API_AUTH: "SETTING_LONGCAT_API_AUTH",
  SETTING_OPENAI_API_AUTH: "SETTING_OPENAI_API_AUTH",
};

export enum EApiProviderType {
  CUSTOM = "custom",
  /** 龙猫 */
  LONG_CAT = "longcat",
  /** 智谱国内站 https://bigmodel.cn/console/overview */
  ZHIPU_CN = "ZHIPU_CN",
  /** 智谱国际站  */
  Z_AI = "Z_AI",
  /** 小米MIMO */
  MIMO = "MIMO",
  /** OpenAI */
  OPEN_AI = "OPEN_AI",
  /** 本地gemma运行 */
  LOCAL_TRANSFORMER = "LOCAL_TRANSFORMER",
  /** Omni类型的模型运行 */
  OMNI = "OMNI",
}
